name: CI to Docker Hub

on:
  push:
    branches: [ main, 'v*.*.*' ]

  pull_request:
    branches: [ main ]

env:
  DEP_PATH: requirements.txt

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@master
        with:
          scan_requirements_file_only: 'true'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push docker image to Docker Hub
        id: docker_build
        run: |
          ./docker-ci.sh
      
      - name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}